const CLUB_NAME_MAP: Record<string, string> = {
  'driver': 'driver',
  'dr': 'driver',
  '1w': 'driver',
  '3-wood': '3-wood',
  '3w': '3-wood',
  '3 wood': '3-wood',
  'three wood': '3-wood',
  '5-wood': '5-wood',
  '5w': '5-wood',
  '5 wood': '5-wood',
  'five wood': '5-wood',
  'hybrid': 'hybrid',
  '4-hybrid': 'hybrid',
  '4h': 'hybrid',
  '3-iron': '3-iron',
  '3i': '3-iron',
  '3 iron': '3-iron',
  '4-iron': '4-iron',
  '4i': '4-iron',
  '4 iron': '4-iron',
  '5-iron': '5-iron',
  '5i': '5-iron',
  '5 iron': '5-iron',
  '6-iron': '6-iron',
  '6i': '6-iron',
  '6 iron': '6-iron',
  '7-iron': '7-iron',
  '7i': '7-iron',
  '7 iron': '7-iron',
  '8-iron': '8-iron',
  '8i': '8-iron',
  '8 iron': '8-iron',
  '9-iron': '9-iron',
  '9i': '9-iron',
  '9 iron': '9-iron',
  'pitching-wedge': 'pitching-wedge',
  'pitching wedge': 'pitching-wedge',
  'pw': 'pitching-wedge',
  'p': 'pitching-wedge',
  'gap-wedge': 'gap-wedge',
  'gap wedge': 'gap-wedge',
  'gw': 'gap-wedge',
  'aw': 'gap-wedge',
  'approach wedge': 'gap-wedge',
  'sand-wedge': 'sand-wedge',
  'sand wedge': 'sand-wedge',
  'sw': 'sand-wedge',
  'lob-wedge': 'lob-wedge',
  'lob wedge': 'lob-wedge',
  'lw': 'lob-wedge',
};

export function normalizeClubName(clubName: string): string | null {
  if (!clubName) return null;
  const normalized = clubName.toLowerCase().trim();
  return CLUB_NAME_MAP[normalized] || null;
}

export function getDisplayName(clubKey: string): string {
  const displayNames: Record<string, string> = {
    'driver': 'Driver',
    '3-wood': '3-Wood',
    '5-wood': '5-Wood',
    'hybrid': 'Hybrid',
    '3-iron': '3-Iron',
    '4-iron': '4-Iron',
    '5-iron': '5-Iron',
    '6-iron': '6-Iron',
    '7-iron': '7-Iron',
    '8-iron': '8-Iron',
    '9-iron': '9-Iron',
    'pitching-wedge': 'PW',
    'gap-wedge': 'GW',
    'sand-wedge': 'SW',
    'lob-wedge': 'LW',
  };
  return displayNames[clubKey] || clubKey;
}

export const DEFAULT_CLUBS = [
  { key: 'driver', name: 'Driver', defaultDistance: 300 },
  { key: '3-wood', name: '3-Wood', defaultDistance: 265 },
  { key: '5-wood', name: '5-Wood', defaultDistance: 245 },
  { key: 'hybrid', name: 'Hybrid', defaultDistance: 225 },
  { key: '4-iron', name: '4-Iron', defaultDistance: 220 },
  { key: '5-iron', name: '5-Iron', defaultDistance: 210 },
  { key: '6-iron', name: '6-Iron', defaultDistance: 198 },
  { key: '7-iron', name: '7-Iron', defaultDistance: 185 },
  { key: '8-iron', name: '8-Iron', defaultDistance: 170 },
  { key: '9-iron', name: '9-Iron', defaultDistance: 153 },
  { key: 'pitching-wedge', name: 'PW', defaultDistance: 145 },
  { key: 'gap-wedge', name: 'GW', defaultDistance: 135 },
  { key: 'sand-wedge', name: 'SW', defaultDistance: 130 },
  { key: 'lob-wedge', name: 'LW', defaultDistance: 120 },
];
